"""
PEFT LoRA Imitation Learning Trainer (Rung 2).

Implements §9.0 and §9.1 of the RL Implementation Plan (v2):
- LoRA config: r=16, lora_alpha=32, lora_dropout=0.05, target_modules=["q_proj", "v_proj", "k_proj", "o_proj"]
- Data: SFT chat-templated JSONL output from dataset.py
- Warm-start gate: requires >= min_trajectories (default 50) before launching real weight training
- Shared dry-run contract: parses config, checks dataset records, validates output dir,
  and exits 0 WITHOUT importing or initializing PyTorch/Transformers/PEFT.
"""

from __future__ import annotations

import argparse

import json
import os

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional
import structlog

from app.rl.registry import AdapterRegistry

logger = structlog.get_logger(__name__)


@dataclass
class SFTConfig:
    """Configuration for SFT LoRA training."""
    model_name_or_path: str = "Qwen/Qwen2.5-7B-Instruct"
    data_path: str = "data/rl/sft.jsonl"
    output_dir: str = "data/rl/adapters/sft"
    lora_r: int = 16
    lora_alpha: int = 32
    lora_dropout: float = 0.05
    target_modules: list[str] = field(
        default_factory=lambda: ["q_proj", "v_proj", "k_proj", "o_proj"]
    )
    learning_rate: float = 2e-4
    epochs: int = 3
    batch_size: int = 4
    max_length: int = 2048
    min_trajectories: int = 50
    dry_run: bool = False


def validate_dataset_records(data_path: str, min_samples: int = 3) -> tuple[int, list[dict[str, Any]]]:
    """Validate data file exists and inspect sample records."""
    p = Path(data_path)
    if not p.exists():
        raise FileNotFoundError(f"SFT dataset file not found at '{data_path}'")

    samples = []
    total = 0
    with open(p, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            total += 1
            if len(samples) < min_samples:
                # Check chat template integrity
                if "messages" not in record or not isinstance(record["messages"], list):
                    raise ValueError(f"Record #{total} missing valid 'messages' list.")
                samples.append(record)

    return total, samples


def run_dry_run(cfg: SFTConfig) -> None:
    """Execute dry-run contract without heavy ML dependencies."""
    print("=" * 65)
    print("[*] SFT TRAINER DRY-RUN VALIDATION")
    print("=" * 65)
    print(f"Base Model:        {cfg.model_name_or_path}")
    print(f"Data Path:         {cfg.data_path}")
    print(f"Output Directory:  {cfg.output_dir}")
    print(f"LoRA Config:       r={cfg.lora_r}, alpha={cfg.lora_alpha}, dropout={cfg.lora_dropout}")
    print(f"Target Modules:    {cfg.target_modules}")
    print(f"Learning Rate:     {cfg.learning_rate} (cosine decay)")
    print(f"Epochs:            {cfg.epochs} | Batch Size: {cfg.batch_size}")
    print("-" * 65)

    # Validate output dir write access
    out = Path(cfg.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    test_file = out / ".write_test"
    test_file.write_text("ok", encoding="utf-8")
    test_file.unlink()
    print("[OK] Output directory validated and writable.")

    # Validate dataset if exists
    if Path(cfg.data_path).exists():
        total, samples = validate_dataset_records(cfg.data_path)
        print(f"[OK] Dataset verified: {total} records found.")
        print(f"[OK] Spot-checked {len(samples)} records (chat template schema intact).")
        if total < cfg.min_trajectories:
            print(f"[INFO] Note: Found {total} trajectories (warm-start gate requires {cfg.min_trajectories} for production).")
    else:
        print(f"[INFO] Dataset file '{cfg.data_path}' does not exist yet (will be generated by dataset.py).")

    # Check registry access
    registry = AdapterRegistry()
    print(f"[OK] Adapter registry access verified (current active: {registry.active_adapter_id or 'None'}).")
    print("-" * 65)
    print("[OK] SFT DRY-RUN COMPLETED SUCCESSFULLY. No ML dependencies constructed.")
    print("=" * 65)


def train_sft(cfg: SFTConfig) -> Optional[str]:
    """Execute SFT training loop on GPU/CPU machine with ML dependencies."""
    if cfg.dry_run:
        run_dry_run(cfg)
        return None

    # Lazy heavy imports (spec §9.0: never at module top)
    try:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer
        from peft import LoraConfig, TaskType
        from trl import SFTTrainer, SFTConfig as TRLSFTConfig
        from datasets import load_dataset
    except ImportError as err:
        logger.error("sft_deps_missing", error=str(err))
        raise RuntimeError(
            "Heavy ML training dependencies missing. "
            "Install GPU requirements via `pip install -r backend/requirements-rl.txt`."
        ) from err

    from app.rl.train_utils import filter_valid_kwargs, ensure_chat_template, resolve_dtype, resolve_device_map

    total, _ = validate_dataset_records(cfg.data_path)
    if total < cfg.min_trajectories:
        logger.warning(
            "sft_warm_start_gate_blocked",
            count=total,
            required=cfg.min_trajectories,
        )
        print(
            f"Warm-start gate blocked: {total} trajectories < {cfg.min_trajectories} required. "
            "Collect more PASS-verified trajectories before training real weights."
        )
        return None

    logger.info("sft_training_started", model=cfg.model_name_or_path, samples=total)

    tokenizer = AutoTokenizer.from_pretrained(cfg.model_name_or_path)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    ensure_chat_template(tokenizer)

    dtype = resolve_dtype()
    device_map = resolve_device_map()
    model = AutoModelForCausalLM.from_pretrained(
        cfg.model_name_or_path,
        torch_dtype=dtype,
        device_map=device_map,
    )

    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=cfg.lora_r,
        lora_alpha=cfg.lora_alpha,
        lora_dropout=cfg.lora_dropout,
        target_modules=cfg.target_modules,
        bias="none",
    )

    # Conversational dataset: SFTTrainer applies the tokenizer's chat template
    # to the `messages` column (spec §5.1 model-native templating at train time).
    ds = load_dataset("json", data_files=cfg.data_path, split="train")
    ds = ds.remove_columns([c for c in ds.column_names if c != "messages"])

    out_dir = Path(cfg.output_dir)
    checkpoint_dir = out_dir / "_checkpoints"
    targs = filter_valid_kwargs(TRLSFTConfig, {
        "output_dir": str(checkpoint_dir),
        "per_device_train_batch_size": cfg.batch_size,
        "num_train_epochs": cfg.epochs,
        "learning_rate": cfg.learning_rate,
        "lr_scheduler_type": "cosine",
        "warmup_ratio": 0.03,
        "logging_steps": 10,
        "save_strategy": "no",  # final adapter saved below
        "max_length": cfg.max_length,
        "bf16": bool(dtype == torch.bfloat16),
        "fp16": bool(dtype == torch.float16),
        "gradient_checkpointing": True,
        "report_to": [],
    })
    training_args = TRLSFTConfig(**targs)

    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=ds,
        processing_class=tokenizer,
        peft_config=peft_config,
    )
    train_result = trainer.train()

    out_dir.mkdir(parents=True, exist_ok=True)
    trainer.save_model(str(out_dir))  # persists the trained LoRA adapter
    tokenizer.save_pretrained(str(out_dir))

    loss_history = [
        entry["loss"] for entry in trainer.state.log_history if "loss" in entry
    ]
    final_loss = loss_history[-1] if loss_history else None

    # Register in adapter registry with real training metrics
    run_id = f"sft_{Path(cfg.output_dir).name}"
    registry = AdapterRegistry()
    registry.register_adapter(
        run_id=run_id,
        rung=2,
        base_model=cfg.model_name_or_path,
        adapter_path=cfg.output_dir,
        metrics={
            "total_samples": total,
            "epochs": cfg.epochs,
            "train_loss_final": final_loss,
            "train_runtime_s": train_result.metrics.get("train_runtime"),
        },
    )

    print(
        f"SFT training completed: {total} samples, {cfg.epochs} epochs, "
        f"final loss={final_loss if final_loss is not None else 'n/a'}. "
        f"Adapter saved to {cfg.output_dir}"
    )
    return cfg.output_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="PEFT LoRA Imitation Learning Trainer (Rung 2)")
    parser.add_argument("--model", type=str, default="Qwen/Qwen2.5-7B-Instruct", help="Base model identifier")
    parser.add_argument("--data", type=str, default="data/rl/sft.jsonl", help="Path to SFT JSONL dataset")
    parser.add_argument("--output_dir", type=str, default="data/rl/adapters/sft", help="Output adapter directory")
    parser.add_argument("--epochs", type=int, default=3, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=4, help="Per device batch size")
    parser.add_argument("--lr", type=float, default=2e-4, help="Learning rate")
    parser.add_argument("--min_trajectories", type=int, default=50, help="Warm-start minimum trajectory gate")
    parser.add_argument("--dry-run", action="store_true", help="Perform validation dry-run without loading ML models")

    args = parser.parse_args()
    cfg = SFTConfig(
        model_name_or_path=args.model,
        data_path=args.data,
        output_dir=args.output_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.lr,
        min_trajectories=args.min_trajectories,
        dry_run=args.dry_run,
    )
    train_sft(cfg)


if __name__ == "__main__":
    main()
